# Generated by Django 3.0.9 on 2020-08-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
