# Generated by Django 3.0.9 on 2020-08-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_currency_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
