# Generated by Django 3.0.9 on 2020-08-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200805_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='sname',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
