# Generated by Django 3.0.9 on 2020-08-06 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200805_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
