# Generated by Django 3.0.9 on 2020-08-06 05:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200805_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 5, 59, 21, 496195, tzinfo=utc)),
        ),
    ]
