# Generated by Django 3.0.9 on 2020-08-06 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200805_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
