# Generated by Django 3.1 on 2020-08-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20200805_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='EURtoUSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=10, max_digits=25)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='fname',
            new_name='base_currency',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='sname',
        ),
        migrations.AddField(
            model_name='currency',
            name='non_base_currency',
            field=models.CharField(default='USD', max_length=255),
            preserve_default=False,
        ),
    ]
