# Generated by Django 3.1 on 2020-09-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_forexexchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestingStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
