# Generated by Django 3.1 on 2020-09-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_investingproduct_investingstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MexExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
