# Generated by Django 3.1 on 2020-09-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_mexexchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
